"""Serve the built React SPA with per-link Open Graph tags.

WhatsApp/Telegram/Facebook link previews are generated by fetching the URL
and reading the <meta property="og:*"> tags from the raw HTML — no JS runs.
Because the SPA ships one static index.html, every shared link would get the
same generic preview. This view rewrites the OG tags per request:

  ?product=<id>       -> product name + first product photo
  ?category=<slug>    -> category name + photo of the first product in it
"""

import html
import json
import random
import re

from django.conf import settings
from django.http import HttpResponse

from catalog.models import Category, Product

SITE_NAME = "TopMax Sanitary"


def _localized(value, fallback=""):
    if not isinstance(value, dict):
        return fallback
    return value.get("ru") or value.get("en") or value.get("kk") or fallback


def _product_image_url(product):
    """First uploaded image (primary first), falling back to legacy image_urls."""
    img = product.images.order_by("-is_primary", "sort_order", "id").first()
    if img:
        return img.image.url
    for url in product.image_urls or []:
        if not url:
            continue
        if not url.startswith(("http://", "https://", "/")):
            url = f"{settings.MEDIA_URL}products/{url}"
        return url
    return None


def _og_overrides(request):
    """Return {'title', 'description', 'image'} for the shared link, or None."""
    product_id = request.GET.get("product", "")
    if product_id.isdigit():
        product = Product.objects.filter(pk=product_id).first()
        if product:
            name = _localized(product.name, product.item_code)
            return {
                "title": f"{name} | {SITE_NAME}",
                "description": _localized(product.description) or None,
                "image": _product_image_url(product),
            }

    category_slug = request.GET.get("category", "")
    if category_slug and category_slug.lower() != "all":
        category = Category.objects.filter(slug=category_slug).first()
        if category:
            image = None
            for product in category.products.all()[:10]:
                image = _product_image_url(product)
                if image:
                    break
            name = _localized(category.name, category.slug)
            return {
                "title": f"{name} | {SITE_NAME}",
                "description": None,
                "image": image,
            }

    return None


def _set_meta(page, prop, value):
    """Replace the content of an existing og meta tag, or add it to <head>."""
    escaped = html.escape(value, quote=True)
    pattern = re.compile(
        rf'(<meta property="{re.escape(prop)}" content=")[^"]*(">)'
    )
    if pattern.search(page):
        return pattern.sub(lambda m: m.group(1) + escaped + m.group(2), page)
    return page.replace(
        "</head>", f'  <meta property="{prop}" content="{escaped}">\n</head>'
    )


def _absolute_https(request, url):
    """Absolute URL for crawlers; force https except on localhost."""
    if not url.startswith(("http://", "https://")):
        url = request.build_absolute_uri(url)
    host = request.get_host().split(":")[0]
    if url.startswith("http://") and host not in ("localhost", "127.0.0.1"):
        url = "https://" + url[len("http://"):]
    return url


def share_preview(request):
    """Link-preview page for WhatsApp/Telegram shares.

    Served under /api/ because on production nginx serves the SPA's
    index.html statically and only proxies /api/ to Django. Crawlers read
    the OG tags from this response; human visitors are redirected straight
    to the SPA category/product view.
    """
    target = _absolute_https(request, "/")
    title = f"{SITE_NAME} | Премиальные решения для ванной в Казахстане"
    description = (
        "TopMax — всё для вашей ванной комнаты в одном месте. "
        "Премиальная сантехника в Казахстане."
    )
    image = None

    product_id = request.GET.get("product", "")
    category_slug = request.GET.get("category", "")

    if product_id.isdigit():
        product = Product.objects.filter(pk=product_id).first()
        if product:
            target = _absolute_https(request, f"/?product={product.pk}")
            title = f"{_localized(product.name, product.item_code)} | {SITE_NAME}"
            description = _localized(product.description) or description
            image = _product_image_url(product)
    elif category_slug and category_slug.lower() != "all":
        category = Category.objects.filter(slug=category_slug).first()
        if category:
            target = _absolute_https(request, f"/?category={category.slug}")
            title = f"{_localized(category.name, category.slug)} | {SITE_NAME}"
            candidates = [
                url
                for product in category.products.all()[:24]
                if (url := _product_image_url(product))
            ]
            if candidates:
                image = random.choice(candidates)

    image_tag = ""
    if image:
        image = _absolute_https(request, image)
        image_tag = (
            f'<meta property="og:image" content="{html.escape(image, quote=True)}">\n'
            '<meta name="twitter:card" content="summary_large_image">\n'
        )

    e_title = html.escape(title, quote=True)
    e_description = html.escape(description, quote=True)
    e_target = html.escape(target, quote=True)
    page = (
        "<!DOCTYPE html>\n"
        '<html lang="ru">\n<head>\n<meta charset="utf-8">\n'
        f"<title>{e_title}</title>\n"
        f'<meta property="og:title" content="{e_title}">\n'
        f'<meta property="og:description" content="{e_description}">\n'
        f'<meta property="og:url" content="{e_target}">\n'
        f'<meta property="og:type" content="website">\n'
        f'<meta property="og:site_name" content="{SITE_NAME}">\n'
        f"{image_tag}"
        f'<meta http-equiv="refresh" content="0;url={e_target}">\n'
        "</head>\n<body>\n"
        f"<script>window.location.replace({json.dumps(target)});</script>\n"
        f'<p><a href="{e_target}">{e_title}</a></p>\n'
        "</body>\n</html>\n"
    )
    return HttpResponse(page)


def spa_index(request, *args, **kwargs):
    page = (settings.FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

    page = _set_meta(page, "og:url", request.build_absolute_uri())

    og = _og_overrides(request)
    if og:
        page = _set_meta(page, "og:title", og["title"])
        if og["description"]:
            page = _set_meta(page, "og:description", og["description"])
        if og["image"]:
            image_url = og["image"]
            if not image_url.startswith(("http://", "https://")):
                image_url = request.build_absolute_uri(image_url)
            page = _set_meta(page, "og:image", image_url)

    return HttpResponse(page)
