"""Serve the built React SPA with per-link Open Graph tags.

WhatsApp/Telegram/Facebook link previews are generated by fetching the URL
and reading the <meta property="og:*"> tags from the raw HTML — no JS runs.
Because the SPA ships one static index.html, every shared link would get the
same generic preview. This view rewrites the OG tags per request:

  ?product=<id>       -> product name + first product photo
  ?category=<slug>    -> category name + photo of the first product in it
"""

import html
import re

from django.conf import settings
from django.http import HttpResponse

from catalog.models import Category, Product

SITE_NAME = "TopMax Sanitary"


def _localized(value, fallback=""):
    if not isinstance(value, dict):
        return fallback
    return value.get("ru") or value.get("en") or value.get("kk") or fallback


def _product_image_url(product):
    """First uploaded image (primary first), falling back to legacy image_urls."""
    img = product.images.order_by("-is_primary", "sort_order", "id").first()
    if img:
        return img.image.url
    for url in product.image_urls or []:
        if not url:
            continue
        if not url.startswith(("http://", "https://", "/")):
            url = f"{settings.MEDIA_URL}products/{url}"
        return url
    return None


def _og_overrides(request):
    """Return {'title', 'description', 'image'} for the shared link, or None."""
    product_id = request.GET.get("product", "")
    if product_id.isdigit():
        product = Product.objects.filter(pk=product_id).first()
        if product:
            name = _localized(product.name, product.item_code)
            return {
                "title": f"{name} | {SITE_NAME}",
                "description": _localized(product.description) or None,
                "image": _product_image_url(product),
            }

    category_slug = request.GET.get("category", "")
    if category_slug and category_slug.lower() != "all":
        category = Category.objects.filter(slug=category_slug).first()
        if category:
            image = None
            for product in category.products.all()[:10]:
                image = _product_image_url(product)
                if image:
                    break
            name = _localized(category.name, category.slug)
            return {
                "title": f"{name} | {SITE_NAME}",
                "description": None,
                "image": image,
            }

    return None


def _set_meta(page, prop, value):
    """Replace the content of an existing og meta tag, or add it to <head>."""
    escaped = html.escape(value, quote=True)
    pattern = re.compile(
        rf'(<meta property="{re.escape(prop)}" content=")[^"]*(">)'
    )
    if pattern.search(page):
        return pattern.sub(lambda m: m.group(1) + escaped + m.group(2), page)
    return page.replace(
        "</head>", f'  <meta property="{prop}" content="{escaped}">\n</head>'
    )


def spa_index(request, *args, **kwargs):
    page = (settings.FRONTEND_DIR / "index.html").read_text(encoding="utf-8")

    page = _set_meta(page, "og:url", request.build_absolute_uri())

    og = _og_overrides(request)
    if og:
        page = _set_meta(page, "og:title", og["title"])
        if og["description"]:
            page = _set_meta(page, "og:description", og["description"])
        if og["image"]:
            image_url = og["image"]
            if not image_url.startswith(("http://", "https://")):
                image_url = request.build_absolute_uri(image_url)
            page = _set_meta(page, "og:image", image_url)

    return HttpResponse(page)
