# Generated by Django 5.2.11 on 2026-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=64, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Baths", "Baths"),
                            ("Basins", "Basins"),
                            ("Taps", "Taps"),
                            ("Closets", "Closets"),
                            ("Mirrors", "Mirrors"),
                            ("Dryers", "Dryers"),
                            ("Others", "Others"),
                            ("Accessories", "Accessories"),
                        ],
                        max_length=32,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("dimensions", models.CharField(blank=True, max_length=128)),
                ("name", models.JSONField(default=dict)),
                ("description", models.JSONField(default=dict)),
                ("features", models.JSONField(default=dict)),
                ("image_urls", models.JSONField(default=list)),
                ("available_colors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
