# Generated by Django 5.2.10 on 2026-02-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
