# Generated by Django 5.2.10 on 2026-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0, help_text="0-100. Set to 0 for no discount."
            ),
        ),
    ]
