# Generated by Django 5.2.10 on 2026-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, help_text="Mark as new arrival."),
        ),
    ]
