# Generated by Django 5.2.10 on 2026-05-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_wholesale_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_normal_price",
            field=models.BooleanField(
                default=False, help_text="Show normal price in frontend."
            ),
        ),
    ]
