# Generated by Django 5.2.10 on 2026-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_show_normal_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_normal_prices",
                    models.BooleanField(
                        default=False,
                        help_text="Show normal prices for all products in frontend.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="show_normal_price",
        ),
    ]
