# Generated by Codex on 2026-05-10

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_sitesettings_remove_product_show_normal_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty",
            field=models.JSONField(
                blank=True,
                default=catalog.models.default_warranty,
            ),
        ),
    ]
