# Generated by Codex on 2026-05-10

import catalog.models
from django.db import migrations, models


def set_empty_warranties_to_default(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(warranty={}).update(warranty=catalog.models.default_warranty())


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_sitesettings_remove_product_show_normal_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty",
            field=models.JSONField(
                blank=True,
                default=catalog.models.default_warranty,
            ),
        ),
        migrations.RunPython(set_empty_warranties_to_default, migrations.RunPython.noop),
    ]
