# Generated by Django 5.2.11 on 2026-06-19 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_sitesettings_wholesale_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="WholesaleDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional name to identify this device/dealer.",
                        max_length=255,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to revoke wholesale access for this device.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_seen_at", "-created_at"],
            },
        ),
    ]
