# Generated by Django 5.2.11 on 2026-07-03 05:32

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_wholesaledevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": [django.db.models.functions.text.Lower("item_code")]},
        ),
    ]
