# Generated by Django 5.2.11 on 2026-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="moysklad_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Linked MoySklad product UUID. Stock is auto-synced for linked products.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
