# Generated by Django 5.2.10 on 2026-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_product_moysklad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Live MoySklad stock count for linked products. Null if unlinked or never synced.",
                null=True,
            ),
        ),
    ]
